# Generated by Django 4.2.5 on 2023-09-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', max_length=200)),
                ('price', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('capacity', models.IntegerField()),
                ('size', models.CharField(default='', max_length=100)),
                ('breakfast', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='')),
                ('img1', models.ImageField(default='', upload_to='')),
                ('img2', models.ImageField(default='', upload_to='')),
                ('img3', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('facilities', models.CharField(max_length=200)),
                ('room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='hotel_app.room')),
            ],
        ),
    ]
