# Generated by Django 4.2.5 on 2023-09-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_booking_ispaid_booking_paidat_booking_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(max_length=250),
        ),
    ]
